buildbot: master_build_kernel: touch only added/copied/modified files
Touching all files coming from previous commit means also touching
removed files which can create weird effects.  For example touching
files coming from merge with v5.14-rc1, caused builds to fail with:

  In file included from include/linux/sunrpc/sched.h:19,
                   from include/linux/sunrpc/auth.h:13,
                   from include/linux/nfs_fs.h:31,
                   from kernel/sysctl.c:55:
  include/linux/sunrpc/xdr.h: In function ‘xdr_encode_hyper’:
  include/linux/sunrpc/xdr.h:153:2: error: implicit declaration of function ‘put_unaligned_be64’; did you mean ‘aligned_be64’? [-Werror=implicit-function-declaration]

  drivers/acpi/battery.c:884:22: error: implicit declaration of function ‘get_unaligned’; did you mean ‘get_cmdline’? [-Werror=implicit-function-declaration]

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>