buildbot: service: Parse /etc/default/locale to fix builtins.UnicodeDecodeError
Starting Buildbot master without LC_ALL and LANG causes Buildbot v2.8.3
(Python v3.6.9) to throw exception:

    2020-08-25 10:22:54+0200 [-] initializing www plugin 'waterfall_view'
    2020-08-25 10:22:54+0200 [-] initializing www plugin 'console_view'
    2020-08-25 10:22:54+0200 [-] initializing www plugin 'grid_view'
    2020-08-25 10:22:54+0200 [-] while starting BuildMaster
       Traceback (most recent call last):
         File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
           result = g.send(result)
         File "sandbox/lib/python3.6/site-packages/buildbot/util/service.py", line 49, in reconfigServiceWithBuildbotConfig
           yield svc.reconfigServiceWithBuildbotConfig(new_config)
         File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
           return _cancellableInlineCallbacks(gen)
         File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
           _inlineCallbacks(None, g, status)
       --- <exception caught here> ---
         File "sandbox/lib/python3.6/site-packages/buildbot/master.py", line 302, in startService
           yield self.reconfigServiceWithBuildbotConfig(self.config)
         File "sandbox/lib/python3.6/site-packages/buildbot/util/service.py", line 49, in reconfigServiceWithBuildbotConfig
           yield svc.reconfigServiceWithBuildbotConfig(new_config)
         File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
           result = g.send(result)
         File "sandbox/lib/python3.6/site-packages/buildbot/www/service.py", line 217, in reconfigServiceWithBuildbotConfig
           self.reconfigSite(new_config)
         File "sandbox/lib/python3.6/site-packages/buildbot/www/service.py", line 352, in reconfigSite
           rsrc.reconfigResource(new_config)
         File "sandbox/lib/python3.6/site-packages/buildbot/www/config.py", line 55, in reconfigResource
           self.custom_templates = self.parseCustomTemplateDir(template_dir)
         File "sandbox/lib/python3.6/site-packages/buildbot/www/config.py", line 87, in parseCustomTemplateDir
           jade = f.read()
         File "sandbox/lib/python3.6/encodings/ascii.py", line 26, in decode
           return codecs.ascii_decode(input, self.errors)[0]
       builtins.UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 2003: ordinal not in range(128)

    2020-08-25 10:22:54+0200 [-] BuildMaster startup failed

Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>