ansible: buildbot-git-mirror: add missing packaging dependency
Fixes:

  File "/usr/local/bin/grok-fsck", line 8, in <module>
    sys.exit(command())
  File "/usr/local/lib/python3.10/dist-packages/grokmirror/fsck.py", line 1391, in command
    return grok_fsck(opts.config, opts.verbose, opts.force, opts.repack_only, opts.conn_only,
  File "/usr/local/lib/python3.10/dist-packages/grokmirror/fsck.py", line 1367, in grok_fsck
    fsck_mirror(config, force, repack_only, conn_only, repack_all_quick, repack_all_full)
  File "/usr/local/lib/python3.10/dist-packages/grokmirror/fsck.py", line 657, in fsck_mirror
    if commitgraph and not grokmirror.git_newer_than('2.18.0'):
  File "/usr/local/lib/python3.10/dist-packages/grokmirror/__init__.py", line 101, in git_newer_than
    from packaging import version
  ModuleNotFoundError: No module named 'packaging'

Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>