buildbot: master: correct Git URL passed to workers
GitPoller on master operates on Git repo URL file:// which is then
passed to workers:

  buildbot.changes.gitpoller.GitError: command ['ls-remote', '--refs', 'file:///var/lib/git/mirror/pub/scm/linux/kernel/git/stable/linux-stable.git'] in None on repourl
  file:///var/lib/git/mirror/pub/scm/linux/kernel/git/stable/linux-stable.git failed with exit code 128:
  fatal: '/var/lib/git/mirror/pub/scm/linux/kernel/git/stable/linux-stable.git' does not appear to be a git repository
  fatal: Could not read from remote repository.

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>