buildbot: master_boot: Fix hang Buildbot on invalid characters during power off
Fixes from commit 080389b402ab ("buildbot: master_boot: Fix stalled
power off step due to unprintable characters") are still needed so bring
them back.  Otherwise the Buildbot hangs on power off step and
eventually shows exception:

    Traceback (most recent call last):
      File "/home/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in errback
        self._startRunCallbacks(fail)
      File "/home/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
        self._runCallbacks()
      File "/home/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/home/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
        _inlineCallbacks(r, g, status)
    --- <exception caught here> ---
      File "/home/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 578, in startStep
        self.results = yield self.run()
      File "/home/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 708, in run
        results = yield self._start_deferred
      File "/home/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
        result = g.send(result)
      File "/home/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 708, in run
        results = yield self._start_deferred
    exceptions.TypeError: 'unicode' does not have the buffer interface

Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>