buildbot: master_build_common: Fix parsing warnings on dt_binding_check
Commit 2fd9e1f81bfc ("buildbot: master: Enable W=1 on dtbs_check and
collect dtc warnings") introduced new warnings pattern for dtbs_check
and changed warnExtractFromRegexpGroups() for parsing match regexp.  It
however did not update the existing pattern for dt_binding_check leading
to usage of different match groups between these:

2026-05-05 10:15:29+0200 [-] while invoking callback <bound method LogObserver.gotData of <buildbot.process.logobserver.LineConsumerLogObserver object at 0x7f86fc1432e0>> to <SubscriptionPoint ''stdio' log'>
  Traceback (most recent call last):
    File "/home/buildbot/sandbox/lib/python3.10/site-packages/buildbot/process/remotecommand.py", line 364, in add_stderr_lines
      await self.logs[self.stdioLogName].add_stderr_lines(data)
    File "/home/buildbot/sandbox/lib/python3.10/site-packages/buildbot/process/log.py", line 212, in add_stderr_lines
      return self._on_whole_lines('e', text)
    File "/home/buildbot/sandbox/lib/python3.10/site-packages/buildbot/process/log.py", line 177, in _on_whole_lines
      self.subPoint.deliver(stream, lines)
    File "/home/buildbot/sandbox/lib/python3.10/site-packages/buildbot/util/subscription.py", line 50, in deliver
      self._notify_delivery_exception(e, sub)
  --- <exception caught here> ---
    File "/home/buildbot/sandbox/lib/python3.10/site-packages/buildbot/util/subscription.py", line 43, in deliver
      d = sub.callback(*args, **kwargs)
    File "/home/buildbot/sandbox/lib/python3.10/site-packages/buildbot/process/logobserver.py", line 41, in gotData
      self.errReceived(data)
    File "/home/buildbot/sandbox/lib/python3.10/site-packages/buildbot/process/logobserver.py", line 90, in errReceived
      self._lineReceived(data, self.stderrDelimiter, self.errLineReceived)
    File "/home/buildbot/sandbox/lib/python3.10/site-packages/buildbot/process/logobserver.py", line 84, in _lineReceived
      funcReceived(line)
    File "/home/buildbot/sandbox/lib/python3.10/site-packages/buildbot/process/logobserver.py", line 128, in errLineReceived
      self.feed(('e', line))
    File "/home/buildbot/sandbox/lib/python3.10/site-packages/buildbot/steps/shell.py", line 367, in warningLogConsumer
      self.maybeAddWarning(self.loggedWarnings, line, match)
    File "/home/buildbot/sandbox/lib/python3.10/site-packages/buildbot/steps/shell.py", line 371, in maybeAddWarning
      (file, lineNo, text) = self.warningExtractor(self, line, match)
    File "/home/buildbot/master/master_build_common.py", line 169, in warnExtractFromRegexpGroups
      text = match.group(3)
  builtins.IndexError: no such group

Fixes: 2fd9e1f81bfc ("buildbot: master: Enable W=1 on dtbs_check and collect dtc warnings")
Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>