tests-var: port100_probe: fix build on ARMv7
Building on armv7l fails because the mmap syscall is not available:

  port100_probe.c: In function ‘execute_one’:
  port100_probe.c:664:11: error: ‘__NR_mmap’ undeclared (first use in this function)
    664 |   syscall(__NR_mmap, 0x20000000ul, 0x800000ul, 0x1800003ul, 0x12ul, r[0], 0ul);
        |           ^~~~~~~~~

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>