buildbot: master_boot: Fix stalled power off step due to unprintable characters
If the last gracefull power off step has unprintable character in serial
log, the step stalls and eventually (on timeout or manual stop) prints
error:
      File "/home/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 707, in run
        results = yield self._start_deferred
    exceptions.TypeError: 'unicode' does not have the buffer interface

Solution is to not store power off output in log but just print it to
stdout while converting the special characters to hex.

Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>