buildbot: Fix booting from multi_v7 defconfig (early probe of modules)
The initial initramfs CPIO file was created from a running machine under
kernel built with exynos defconfig.  This created the initramfs with
MODULE="" in /config.  Such initramfs does not load network adapter
driver early and does not boot:

    [   15.210415] Run /init as init process
    :: running early hook [udev]
    starting version 236
    :: running hook [udev]
    :: Triggering uevents...
    [   15.974687] samsung-usb2-phy 12130000.phy: 12130000.phy supply vbus not found, using dummy regulator
    [   15.975634] ohci-exynos: OHCI EXYNOS driver
    [   15.982750] samsung-usb2-phy 12130000.phy: Linked as a consumer to regulator.0
    [   15.994951] exynos-ohci 12120000.usb: USB Host Controller
    [   15.996753] exynos-ehci 12110000.usb: EHCI Host Controller
    [   15.999127] exynos-ohci 12120000.usb: new USB bus registered, assigned bus number 5
    [   16.004545] exynos-ehci 12110000.usb: new USB bus registered, assigned bus number 6
    [   16.022045] exynos-ohci 12120000.usb: irq 84, io mem 0x12120000
    [   16.023079] exynos-ehci 12110000.usb: irq 84, io mem 0x12110000
    [   16.038122] s5m-rtc s2mps14-rtc: rtc core: registered s5m-rtc as rtc0
    [   16.058695] exynos-ehci 12110000.usb: USB 2.0 started, EHCI 1.00
    [   16.064913] hub 6-0:1.0: USB hub found
    [   16.068802] hub 6-0:1.0: 3 ports detected
    [   16.077147] usbcore: registered new interface driver r8152
    [   16.095231] hub 5-0:1.0: USB hub found
    [   16.098580] hub 5-0:1.0: 3 ports detected
    :: running hook [net_nfs4]
    ipconfig: eth0: SIOCGIFINDEX: No such device
    ipconfig: no devices to configure
    NFS-Mount: 192.168.1.10:/srv/nfs/odroidhc1
    [   16.260694] usb 3-1: reset high-speed USB device number 2 using xhci-hcd
    Waiting 10 seconds for device /dev/nfs ...
    [   16.521888] r8152 3-1:1.0 eth0: v1.09.9
    Mount cmd:
    mount.nfs4 -o vers=4,nolock 192.168.1.10:/srv/nfs/odroidhc1 /new_root
    [   26.923032] NFS: bad mount option value specified: minorversion=1
    mount.nfs4: Network is unreachable
    :: running cleanup hook [udev]
    ERROR: Failed to mount the real root device.

Make a custom config (with proper MODULES entry) so the r8152 or any
other driver will be loaded early.  The same effect would be to either
go back to mkinitcpio method (since Raspberry Pi 3 is now ARMv7) or
create the initial initramfs CPIO archive from a multi_v7 booted kernel.

Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>