buildbot: master: fixup builder prioritizing due to comparison of deferred
Prioritizing was not working since some time with errors:

2021-08-06 14:44:22+0200 [-] prioritizing builders; order unspecified
        Traceback (most recent call last):
          File "/home/buildbot/sandbox/lib/python3.6/site-packages/buildbot/process/buildrequestdistributor.py", line 354, in resetPendingBuildersList
            list(existing_pending | new_builders))
          File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
          File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
        --- <exception caught here> ---
          File "/home/buildbot/sandbox/lib/python3.6/site-packages/buildbot/process/buildrequestdistributor.py", line 430, in _sortBuilders
            builders = yield sorter(self.master, builders)
          File "/home/buildbot/master/master.cfg", line 254, in prioritize_builders
            reverse=False)
        builtins.TypeError: '<' not supported between instances of 'Deferred' and 'Deferred'

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>